export const postsPerPagesCount = 10;
export const maxPostsPerPagesCount = 20;
export const tasksPerPagesCount = 8;
export const maxTasksPerPagesCount = 16;
export const taskCommentsPerPagesCount = 10;
export const maxTaskCommentsPerPagesCount = 20;
export const messagesPerPagesCount = 10;
export const maxMessagesPerPagesCount = 20;
export const SolutionStatus = { EMPTY: 1, LOADING: 2, LOADED: 3, TESTING: 4, TESTED: 5 };
